name: PilottAI Pull Request
description: Submit changes to the PilottAI framework
title: "[TYPE]: "
body:
  - type: markdown
    attributes:
      value: |
        # PilottAI Pull Request
        Thank you for contributing to PilottAI! Please fill out the information below to help reviewers understand your changes.

  - type: dropdown
    id: change-type
    attributes:
      label: Type of Change
      description: What kind of change does this PR introduce?
      options:
        - Bug fix (non-breaking change that fixes an issue)
        - New feature (non-breaking change that adds functionality)
        - Breaking change (fix or feature that would change existing functionality)
        - Documentation update
        - Performance improvement
        - Code cleanup or refactor
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a summary of your changes
      placeholder: Explain what this PR does and why it should be accepted
    validations:
      required: true

  - type: input
    id: issue-link
    attributes:
      label: Related Issue
      description: Link to the issue this PR addresses
      placeholder: "Fixes #123 or Related to #456"

  - type: textarea
    id: testing
    attributes:
      label: Testing Performed
      description: Describe the tests you ran to verify your changes
      placeholder: "Include details of your testing environment and how you tested these changes"
    validations:
      required: true

  - type: checkboxes
    id: testing-checklist
    attributes:
      label: Testing Checklist
      description: Select all that apply
      options:
        - label: Unit tests added/modified
        - label: Integration tests performed
        - label: Manual testing completed
        - label: Test coverage is maintained or improved

  - type: checkboxes
    id: quality-checklist
    attributes:
      label: Quality Checklist
      description: Please confirm the following
      options:
        - label: My code follows the project's coding standards
          required: true
        - label: Code is properly typed with type hints
        - label: Docstrings follow Google style
        - label: Documentation has been updated (if necessary)
        - label: Code passes all linters (black, isort, flake8)

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies that were added or updated
      placeholder: "Example: Added pandas 2.0.1, Updated numpy to 1.25.0"

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any other context about the PR here
      placeholder: "Screenshots, special deployment considerations, areas that need particular review, etc."
