name: Feature Request
description: Suggest a new feature for PilottAI framework
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for PilottAI.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: |
        What alternative approaches have you thought about?
        What are their pros and cons?

  - type: textarea
    id: example
    attributes:
      label: Example Implementation
      description: If possible, provide an example of how this feature might work
      render: python
      placeholder: |
        from pilott import Serve

        # Example code showing how the feature might be used

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: |
        - Use cases
        - Impact on existing functionality
        - Performance considerations
        - Security implications

  - type: textarea
    id: requirements
    attributes:
      label: Technical Requirements
      description: List any technical requirements or dependencies
      placeholder: |
        - Required dependencies
        - System requirements
        - Performance requirements
        - Compatibility requirements