name: Deploy Interface to S3

on:
  pull_request:
    branches: [ 'dev' ]
    paths:
      - 'interface/src/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync interface/src/ s3://${{ secrets.S3_BUCKET }}/ \
            --delete \
            --cache-control "max-age=86400" \
            --exclude "*.git/*" \
            --exclude "*.github/*" \
            --exclude "node_modules/*" \
            --exclude "*.DS_Store"

      - name: Invalidate CloudFront cache
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/src/*"

      - name: Deployment status notification
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}'
            const message = status === 'success'
              ? '✅ Interface deployment to S3 completed successfully'
              : '❌ Interface deployment to S3 failed'
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message
            })
