name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install and configure Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="/home/runner/.local/bin:$PATH"
        poetry config virtualenvs.create false

    - name: Install poetry-dynamic-versioning
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        poetry self add "poetry-dynamic-versioning[plugin]"

    - name: Fix lock file
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        rm -f poetry.lock
        poetry lock

    - name: Install dependencies
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        poetry install --no-root

    - name: Build package
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        poetry build

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        poetry publish